### ISSUE TITLE
Control as default input

### ISSUE THREAD

**Issue by secminhr** [Grapycal/Grapycal#35]
related item: https://github.com/orgs/Grapycal/projects/2?pane=issue&itemId=49335708

Functions are maybe ready. Layout isn't working.

I use following node declaration to test this, it's not committed:
```python3
class TestDefaultNode(Node):
    category = 'procedural'

    def build_node(self):
        super().build_node()
        self.label.set('Test default')
        self.shape.set('normal')
        self.in_port = self.add_control_default_in_port(
            'test_in', TextControl
        )
        self.add_text_control('str', 'control_label')
        self.out_port = self.add_out_port('test_out')

    def edge_activated(self, edge:Edge, port:InputPort):
        self.out_port.push_data(self.in_port.get_one_data())

    def double_click(self):
        self.out_port.push_data(self.in_port.get_one_data())

```

**Comment by eri24816** [comment]
I tend to merge add_control_default_in_port into add_in_port

**Comment by secminhr** [comment]
That way, you'll need to check the arguments and decide between `InputPort` or `ControlDefaultInputPort` inside `add_in_port` because Python3 doesn't have function overload.

The other way around is to combine `InputPort` and `ControlDefaultInputPort` into a new and only `InputPort`.

**Comment by secminhr** [comment]
Please move to https://github.com/Grapycal/Grapycal/issues/36 for further discussion.
