### ISSUE TITLE
drop-down list in Nodes

### ISSUE THREAD

**Issue by weihsinyeh** [Grapycal/Grapycal#39]
Some nodes need a dropdown menu, taking trigonometric functions as an example. There is a node called 'Trigonometric Functions,' and when the user right-clicks on this node, a list will appear with six options: sin, cos, tan, sec, csc, cot. When the user selects a mathematical operation, the node's name should change from 'Trigonometric Functions' to the selected function (e.g., 'sin'), and it should perform the corresponding mathematical operation inside the node.

For example : 
trigonometric functions
|- sin
|- cos
|- tan
|- cot
|- sec
|- csc

**There are two main advantages of this approach.** 
First, it simplify the complexity of the left-side "node list". 
Secondly, It allows users to quickly switch between functions without the need to reprocess input and output, enhancing efficiency.

**Comment by eri24816** [comment]
Done. From now on (on dev branch), you can add an option control in your node with Node.add_option_control() method. For example:

```python
class OptionControlExampleNode(Node):
    category = 'function'

    def build_node(self):
        self.label.set('Select a fruit')
        self.option_control = self.add_option_control(
            options=['apple','banana','orange'],
            value='apple',
            label='Fruit'
        )
        self.out_port = self.add_out_port('out')

    def init_node(self):
        self.option_control.on_set += self.option_changed

    def option_changed(self,value:str):
        self.out_port.push_data(value)
```

![Image](https://github.com/Grapycal/Grapycal/assets/30017117/c75678ed-d6b5-4adb-94f1-78f749f3278d)
