### ISSUE TITLE
Unable to install grapycal in python venv

### ISSUE THREAD

**Issue by HanYuanHsu** [Grapycal/Grapycal#44]
Hi, I was unable to do `pip install grapycal grapycal-builtin` in a python venv inside an Ubuntu WSL. I got the following error message:
```
ERROR: Could not find a version that satisfies the requirement grapycal (from versions: none)
ERROR: No matching distribution found for grapycal
```

The venv was created by `python3 -m venv grapycal`. The python version is 3.10.12, and the Ubuntu version is 22.04.2 LTS (it is WSL). 

Any help will be appreciated.

**Comment by eri24816** [comment]
Hi, the error is possibly due to an incompatible python version. Please make sure you're using Python 3.11. If the problem persists, please let me know. :D
