### ISSUE TITLE
Crashes when loading examples or local files

### ISSUE THREAD

**Issue by Junhua9981** [Grapycal/Grapycal#45]
## Description
When attempting to load examples or local files using Python version 3.11.0 in a venv environment, grapycal.core.background_runner consistently captures a KeyboardInterrupt, leading to the shutdown of the backend server.

## Versions:
* Python Version: 3.11.0
* Grapycal Versions:
  * grapycal-0.10.0
  * grapycal-builtin-0.10.0

## Details:
Upon attempting to load either examples or local files, the grapycal.core.background_runner module interrupts the process with a KeyboardInterrupt, resulting in the backend server's termination. This behavior occurs consistently, hindering the smooth functioning of the application.
![image](https://github.com/Grapycal/Grapycal/assets/62870545/449600df-f588-4886-9858-96ab5729d192)

## Steps to Reproduce:
Set up a Python 3.11.0 environment using venv. `py -3.11 -m venv venv` `venv/Script/activate`
Install grapycal-0.10.0 and grapycal-builtin-0.10.0. `pip install grapycal grapycal-builtin`
Launch grapycal. `grapycal`
Attempt to load examples or local files within the application.

## Expected Behavior:
Loading examples or local files should not trigger a KeyboardInterrupt, and the backend server should continue running smoothly without interruptions.

**Comment by eri24816** [comment]
Thank you for reporting the issue. Which OS were you using?

**Comment by Junhua9981** [comment]
I'm using windows 11 21H2

版本	Windows 11 家用版
版本	21H2
安裝於	‎2022/‎1/‎2
OS 組建	22000.2538
體驗	Windows 功能體驗套件 1000.22001.1000.0

**Comment by eri24816** [comment]
The problem has been solved in the latest release v0.11.1. Please update Grapycal with `pip install grapycal==0.11.1 grapycal-builtin==0.11.1`.

**Comment by Junhua9981** [comment]
It works as charm. Thanks for your contribution.
